// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YunDa.ISAS.EntityFrameworkCore.EntityFrameworkCore;

namespace YunDa.ISAS.Migrations
{
    [DbContext(typeof(ISASDbContext))]
    partial class ISASDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("YunDa.ISAS.Entities.GeneralInformation.EquipmentInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("CreatorUserId");

                    b.Property<Guid?>("EquipmentTypeId");

                    b.Property<DateTime?>("InstallationDate");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<Guid?>("LastModifierUserId");

                    b.Property<Guid?>("ManufacturerInfoId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime?>("ProductionDate");

                    b.Property<string>("Remark")
                        .HasMaxLength(200);

                    b.Property<Guid?>("TransformerSubstationId");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentTypeId");

                    b.HasIndex("ManufacturerInfoId");

                    b.HasIndex("TransformerSubstationId");

                    b.ToTable("gi_equipment_info");
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.GeneralInformation.EquipmentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("CreatorUserId");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<Guid?>("LastModifierUserId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("gi_equipment_type");
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.GeneralInformation.ManufacturerInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("CreatorUserId");

                    b.Property<Guid?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(50);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<Guid?>("LastModifierUserId");

                    b.Property<string>("ManufacturerAddress")
                        .HasMaxLength(200);

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(29);

                    b.Property<string>("Remark")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("gi_manufacturer_info");
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.GeneralInformation.PowerSupplyLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("CreatorUserId");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<Guid?>("LastModifierUserId");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Remark")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("gi_power_supply_line");
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.GeneralInformation.TransformerSubstation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CommMgrIP")
                        .HasMaxLength(20);

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("CreatorUserId");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<Guid?>("LastModifierUserId");

                    b.Property<Guid?>("PowerSupplyLineId");

                    b.Property<string>("Remark")
                        .HasMaxLength(200);

                    b.Property<string>("SubstationName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("PowerSupplyLineId");

                    b.ToTable("gi_transformer_substation");
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.System.SysFunction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("CreatorUserId");

                    b.Property<string>("Icon")
                        .HasMaxLength(40);

                    b.Property<bool>("IsActive");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<Guid?>("LastModifierUserId");

                    b.Property<string>("LoadUrl")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Remark")
                        .HasMaxLength(200);

                    b.Property<int>("SeqNo");

                    b.Property<Guid?>("SysFunctionId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("sys_function");
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.System.SysRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("CreatorUserId");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<Guid?>("LastModifierUserId");

                    b.Property<string>("Remark")
                        .HasMaxLength(200);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("sys_role");
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.System.SysRoleFunction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("CreatorUserId");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsEdit");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<Guid?>("LastModifierUserId");

                    b.Property<Guid?>("SysFunctionId");

                    b.Property<Guid?>("SysRoleId");

                    b.HasKey("Id");

                    b.HasIndex("SysFunctionId");

                    b.HasIndex("SysRoleId");

                    b.ToTable("sys_role_function");
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.System.SysUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("CreatorUserId");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(50);

                    b.Property<bool>("IsActive");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<Guid?>("LastModifierUserId");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(29);

                    b.Property<string>("RealName")
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("sys_user");
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.System.SysUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("CreatorUserId");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<Guid?>("LastModifierUserId");

                    b.Property<Guid?>("SysRoleId");

                    b.Property<Guid?>("SysUserId");

                    b.HasKey("Id");

                    b.HasIndex("SysRoleId");

                    b.ToTable("sys_user_role");
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.VideoSurveillance.InspectionCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("CreatorUserId");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<Guid?>("LastModifierUserId");

                    b.Property<string>("Remark")
                        .HasMaxLength(200);

                    b.Property<Guid?>("TransformerSubstationId");

                    b.HasKey("Id");

                    b.HasIndex("TransformerSubstationId");

                    b.ToTable("vs_inspection_card");
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.VideoSurveillance.InspectionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("CreatorUserId");

                    b.Property<Guid?>("InspectionCardId");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsImageRecognition");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<Guid?>("LastModifierUserId");

                    b.Property<Guid?>("PresetPointId");

                    b.Property<int>("ProcessAction");

                    b.Property<int>("ProcessDuration");

                    b.Property<string>("Remark")
                        .HasMaxLength(200);

                    b.Property<int>("SeqNo");

                    b.Property<Guid?>("VideoDevId");

                    b.HasKey("Id");

                    b.HasIndex("InspectionCardId");

                    b.HasIndex("PresetPointId");

                    b.HasIndex("VideoDevId");

                    b.ToTable("vs_inspection_Item");
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.VideoSurveillance.InspectionPlanTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("CreatorUserId");

                    b.Property<string>("ExecutionTime")
                        .IsRequired();

                    b.Property<int>("ExecutionWeek");

                    b.Property<Guid?>("InspectionCardId");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<Guid?>("LastModifierUserId");

                    b.Property<string>("PlanTaskName")
                        .HasMaxLength(100);

                    b.Property<string>("Remark")
                        .HasMaxLength(200);

                    b.Property<int>("SeqNo");

                    b.HasKey("Id");

                    b.HasIndex("InspectionCardId");

                    b.ToTable("vs_inspection_plan_task");
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.VideoSurveillance.PresetPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("CreatorUserId");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<Guid?>("LastModifierUserId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Number");

                    b.Property<string>("Remark")
                        .HasMaxLength(200);

                    b.Property<Guid?>("VideoDevId");

                    b.HasKey("Id");

                    b.HasIndex("VideoDevId");

                    b.ToTable("vs_preset_point");
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.VideoSurveillance.VideoDev", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ChannelNo");

                    b.Property<int>("CodeStreamType");

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("CreatorUserId");

                    b.Property<string>("DevName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("DevNo");

                    b.Property<string>("DevPassword")
                        .HasMaxLength(30);

                    b.Property<int>("DevType");

                    b.Property<string>("DevUserName")
                        .HasMaxLength(30);

                    b.Property<string>("IP")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("InstallationDate");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsPTZ");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<Guid?>("LastModifierUserId");

                    b.Property<Guid?>("ManufacturerInfoId");

                    b.Property<int?>("Port");

                    b.Property<DateTime?>("ProductionDate");

                    b.Property<string>("Remark")
                        .HasMaxLength(200);

                    b.Property<int?>("SeqNo");

                    b.Property<Guid?>("TransformerSubstationId");

                    b.Property<Guid?>("VideoDevId");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerInfoId");

                    b.HasIndex("TransformerSubstationId");

                    b.ToTable("vs_video_dev");
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.VideoSurveillance.VideoDevEquipmentInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("CreatorUserId");

                    b.Property<Guid?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<Guid?>("EquipmentInfoId");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<Guid?>("LastModifierUserId");

                    b.Property<string>("Remark")
                        .HasMaxLength(200);

                    b.Property<Guid?>("TransformerSubstationId");

                    b.Property<Guid?>("VideoDevId");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentInfoId");

                    b.HasIndex("TransformerSubstationId");

                    b.HasIndex("VideoDevId");

                    b.ToTable("vs_video_dev_equipment_info");
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.GeneralInformation.EquipmentInfo", b =>
                {
                    b.HasOne("YunDa.ISAS.Entities.GeneralInformation.EquipmentType", "EquipmentType")
                        .WithMany()
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("YunDa.ISAS.Entities.GeneralInformation.ManufacturerInfo", "ManufacturerInfo")
                        .WithMany()
                        .HasForeignKey("ManufacturerInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("YunDa.ISAS.Entities.GeneralInformation.TransformerSubstation", "TransformerSubstation")
                        .WithMany()
                        .HasForeignKey("TransformerSubstationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.GeneralInformation.TransformerSubstation", b =>
                {
                    b.HasOne("YunDa.ISAS.Entities.GeneralInformation.PowerSupplyLine", "PowerSupplyLine")
                        .WithMany("TransformerSubstations")
                        .HasForeignKey("PowerSupplyLineId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.System.SysRoleFunction", b =>
                {
                    b.HasOne("YunDa.ISAS.Entities.System.SysFunction", "SysFunction")
                        .WithMany()
                        .HasForeignKey("SysFunctionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("YunDa.ISAS.Entities.System.SysRole", "SysRole")
                        .WithMany()
                        .HasForeignKey("SysRoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.System.SysUserRole", b =>
                {
                    b.HasOne("YunDa.ISAS.Entities.System.SysRole", "SysRole")
                        .WithMany()
                        .HasForeignKey("SysRoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("YunDa.ISAS.Entities.System.SysUser", "SysUser")
                        .WithMany()
                        .HasForeignKey("SysRoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.VideoSurveillance.InspectionCard", b =>
                {
                    b.HasOne("YunDa.ISAS.Entities.GeneralInformation.TransformerSubstation", "TransformerSubstation")
                        .WithMany("InspectionCards")
                        .HasForeignKey("TransformerSubstationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.VideoSurveillance.InspectionItem", b =>
                {
                    b.HasOne("YunDa.ISAS.Entities.VideoSurveillance.InspectionCard", "InspectionCard")
                        .WithMany("InspectionItems")
                        .HasForeignKey("InspectionCardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("YunDa.ISAS.Entities.VideoSurveillance.PresetPoint", "PresetPoint")
                        .WithMany("InspectionItems")
                        .HasForeignKey("PresetPointId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("YunDa.ISAS.Entities.VideoSurveillance.VideoDev", "VideoDev")
                        .WithMany("InspectionItems")
                        .HasForeignKey("VideoDevId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.VideoSurveillance.InspectionPlanTask", b =>
                {
                    b.HasOne("YunDa.ISAS.Entities.VideoSurveillance.InspectionCard", "InspectionCard")
                        .WithMany("InspectionPlanTasks")
                        .HasForeignKey("InspectionCardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.VideoSurveillance.PresetPoint", b =>
                {
                    b.HasOne("YunDa.ISAS.Entities.VideoSurveillance.VideoDev", "VideoDev")
                        .WithMany("PresetPoints")
                        .HasForeignKey("VideoDevId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.VideoSurveillance.VideoDev", b =>
                {
                    b.HasOne("YunDa.ISAS.Entities.GeneralInformation.ManufacturerInfo", "ManufacturerInfo")
                        .WithMany()
                        .HasForeignKey("ManufacturerInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("YunDa.ISAS.Entities.GeneralInformation.TransformerSubstation", "TransformerSubstation")
                        .WithMany("VideoDevs")
                        .HasForeignKey("TransformerSubstationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("YunDa.ISAS.Entities.VideoSurveillance.VideoDevEquipmentInfo", b =>
                {
                    b.HasOne("YunDa.ISAS.Entities.GeneralInformation.EquipmentInfo", "EquipmentInfo")
                        .WithMany()
                        .HasForeignKey("EquipmentInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("YunDa.ISAS.Entities.GeneralInformation.TransformerSubstation", "TransformerSubstation")
                        .WithMany()
                        .HasForeignKey("TransformerSubstationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("YunDa.ISAS.Entities.VideoSurveillance.VideoDev", "VideoDev")
                        .WithMany()
                        .HasForeignKey("VideoDevId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
